# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [slack, golf]
patreon: # Replace with a single Patreon username corona
open_collective: # Replace with a single Open Collective username mobi.com
ko_fi: # Replace with a single Ko-fi username Cardi
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username bass
issuehunt: # Replace with a single IssueHunt username AMP
otechie: # Replace with a single Otechie username wiki
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://bluebunny.com', 'https://justinfamily.family.blog','https://Dreamhome.org','https://dollarshaveclub.com','https://Amazon.com']
